name: comon_logger
description: A modular, extensible logging library for Dart. Core package with zero dependencies.
version: 0.1.2
resolution: workspace
homepage: https://github.com/serezhia/comon_logger
repository: https://github.com/serezhia/comon_logger/tree/main/packages/comon_logger
issue_tracker: https://github.com/serezhia/comon_logger/issues
topics:
  - logging
  - logger
  - log
  - debug

environment:
  sdk: ^3.9.0

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
