name: shelf_app_example
description: Shelf server example demonstrating comon_logger for backend applications.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.8

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  comon_logger: 0.1.1
  comon_logger_file: 0.1.1

dev_dependencies:
  lints: ^4.0.0
