name: comon_logger_share_flutter
description: Share/export action for comon_logger log viewer screen.
version: 0.1.1
homepage: https://github.com/serezhia/comon_logger
repository: https://github.com/serezhia/comon_logger/tree/main/comon_logger_share_flutter
issue_tracker: https://github.com/serezhia/comon_logger/issues
topics:
  - logging
  - share
  - flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  comon_logger: ^0.1.1
  comon_logger_flutter: ^0.1.1
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
