name: comon_logger_file
description: File-based log handler for comon_logger with log rotation.
version: 0.1.2
resolution: workspace
homepage: https://github.com/serezhia/comon_logger
repository: https://github.com/serezhia/comon_logger/tree/main/packages/comon_logger_file
issue_tracker: https://github.com/serezhia/comon_logger/issues
topics:
  - logging
  - file
  - log-rotation

environment:
  sdk: ^3.9.0

dependencies:
  comon_logger: ^0.1.2

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
